# Generated by Django 6.1.1 on 2026-09-19 13:19

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='The filed is saved news category name', max_length=225, verbose_name='Category Name')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(help_text='The filed is saved news title', max_length=225, verbose_name='News Title')),
                ('description', models.TextField(help_text='The filed is saved news description', verbose_name='News Description')),
                ('image', models.ImageField(blank=True, help_text='The filed is saved news image', null=True, upload_to='news/', verbose_name='News Image')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='The filed is saved news content', verbose_name='News Content')),
                ('category', models.ForeignKey(blank=True, help_text='The filed is saved news category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.newscategory', verbose_name='News Category')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
