# Generated by Django 6.1.1 on 2026-09-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'News Category', 'verbose_name_plural': 'News Categories'},
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='description',
            field=models.TextField(help_text='The filed is saved news category description', verbose_name='Category Description'),
        ),
    ]
