# Generated by Django 6.1.1 on 2026-09-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newscategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, help_text='The filed is saved news description', null=True, verbose_name='News Description'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='description',
            field=models.TextField(blank=True, help_text='The filed is saved news category description', null=True, verbose_name='Category Description'),
        ),
    ]
