# Generated by Django 6.1.1 on 2026-10-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newscategory',
            name='description',
        ),
    ]
